#!/usr/bin/env python
from __future__ import print_function

import rospy
import packager_v1

if __name__ == '__main__':
    try:
        packager_v1.start()
    except rospy.ROSInterruptException:
        pass
